server:
  port: 8080
  tomcat:
    max-threads: 200
    min-spare-threads: 10

spring:
  profiles: prod
  
  datasource:
    url: jdbc:oracle:thin:@${DB_HOST}:${DB_PORT}:${DB_SID}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 20000
      
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        jdbc:
          batch_size: 20
        order_inserts: true

llm:
  vllm:
    enabled: true
    base-url: ${VLLM_BASE_URL}
    timeout: 60
    max-tokens: 1024
    temperature: 0.7
    
  sglang:
    enabled: true
    base-url: ${SGLANG_BASE_URL}
    timeout: 60
    max-tokens: 1024
    temperature: 0.7

logging:
  level:
    com.example.simple: INFO
    org.springframework.web.reactive: WARN
  file:
    name: logs/simple-llm-backend.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30