-- 개발환경용 데이터베이스 스키마 (H2)
-- H2는 Oracle 호환 모드로 실행됨

-- LLM 요청/응답 로그 테이블
CREATE TABLE IF NOT EXISTS LLM_LOGS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    REQUEST_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ENGINE VARCHAR(50) NOT NULL,
    PROMPT CLOB,
    RESPONSE CLOB,
    RESPONSE_TIME_MS BIGINT,
    SUCCESS BOOLEAN DEFAULT TRUE,
    ERROR_MESSAGE VARCHAR(1000),
    REQUEST_IP VARCHAR(45),
    USER_AGENT VARCHAR(500)
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS IDX_LLM_LOGS_TIME ON LLM_LOGS(REQUEST_TIME);
CREATE INDEX IF NOT EXISTS IDX_LLM_LOGS_ENGINE ON LLM_LOGS(ENGINE);
CREATE INDEX IF NOT EXISTS IDX_LLM_LOGS_SUCCESS ON LLM_LOGS(SUCCESS);

-- 시스템 메트릭 테이블 (선택사항)
CREATE TABLE IF NOT EXISTS SYSTEM_METRICS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    METRIC_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    METRIC_NAME VARCHAR(100) NOT NULL,
    METRIC_VALUE DECIMAL(15,4),
    METRIC_UNIT VARCHAR(20)
);

CREATE INDEX IF NOT EXISTS IDX_METRICS_TIME ON SYSTEM_METRICS(METRIC_TIME);
CREATE INDEX IF NOT EXISTS IDX_METRICS_NAME ON SYSTEM_METRICS(METRIC_NAME);