version: '3.7'
services:
  simple-llm-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - VLLM_BASE_URL=http://host.docker.internal:8000
      - SGLANG_BASE_URL=http://host.docker.internal:30000